apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-ark-config
  namespace: heptio-ark
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: deploy-ark-config
      namespace: heptio-ark
    spec:
      restartPolicy: Never
      containers:
        - name: deploy-ark-config
          image: claranet/gcloud-kubectl-docker
          imagePullPolicy: Always
          command: ["kubectl","create","-f","/tmp/"]
          volumeMounts:
            - name: ark-server-config
              mountPath: /tmp
      volumes:
        - name: ark-server-config
          configMap:
            name: ark-server-config
      serviceAccountName: ark
