{{- define "awsCredentials" }}
{{- printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s\n" .Values.AWS_AK .Values.AWS_SK | b64enc }}
{{- end }}
apiVersion: v1
data:
  cloud: {{ template "awsCredentials" . }}
kind: Secret
metadata:
  name: cloud-credentials
type: Opaque
